const baseUrl = process.env.BASE_URL ?? "http://localhost:3000";

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

async function request(path, init = {}) {
  const response = await fetch(`${baseUrl}${path}`, init);
  let json = null;
  try {
    json = await response.json();
  } catch {
    // Not all endpoints return JSON.
  }

  if (!response.ok) {
    const errorMessage = json && typeof json.error === "string" ? json.error : `${response.status} ${response.statusText}`;
    throw new Error(`${path} failed: ${errorMessage}`);
  }

  return { response, json };
}

async function waitForServer(timeoutMs = 60000) {
  const startedAt = Date.now();

  while (Date.now() - startedAt < timeoutMs) {
    try {
      await request("/api/health");
      return;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }

  throw new Error(`Server did not become ready within ${timeoutMs}ms.`);
}

async function run() {
  await waitForServer();
  console.log(`[smoke] Server ready at ${baseUrl}`);

  const runId = Date.now();
  const email = `smoke+${runId}@example.com`;
  const deviceId = `smoke-device-${runId}`;
  const listingId = `smoke-listing-${runId}`;
  const now = new Date().toISOString();

  const signIn = await request("/api/auth/sign-in", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      email,
      name: "Smoke Test User"
    })
  });
  assert(signIn.json?.email === email, "Sign-in response did not return the expected email.");
  console.log("[smoke] Auth sign-in passed");

  const listingPayload = {
    id: listingId,
    mode: "buy",
    title: "Smoke test listing for backend",
    description: "This listing is generated by the smoke test to validate database persistence.",
    country: "United States",
    city: "Austin",
    address: "100 Smoke Test Avenue",
    lat: 30.2672,
    lng: -97.7431,
    price: { salePrice: 450000 },
    currency: "USD",
    beds: 3,
    baths: 2,
    areaSqm: 120,
    propertyType: "house",
    images: ["https://picsum.photos/seed/smoke/1200/800"],
    amenities: ["Wi-Fi", "Parking"],
    hostType: "agent",
    createdAt: now
  };

  const createListing = await request("/api/listings", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-user-email": email,
      "x-device-id": deviceId
    },
    body: JSON.stringify({ listing: listingPayload })
  });
  assert(createListing.json?.id === listingId, "Listing create response did not return the new ID.");
  console.log("[smoke] Listing creation passed");

  const getListing = await request(`/api/listings/${listingId}`);
  assert(getListing.json?.id === listingId, "Listing lookup failed.");
  console.log("[smoke] Listing retrieval passed");

  const searchResults = await request("/api/listings/search", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ mode: "buy", text: "Austin" })
  });
  assert(Array.isArray(searchResults.json), "Search response is not an array.");
  assert(searchResults.json.some((entry) => entry.id === listingId), "Search did not include the created listing.");
  console.log("[smoke] Listing search passed");

  const toggleSaved = await request("/api/saved/listings", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-user-email": email,
      "x-device-id": deviceId
    },
    body: JSON.stringify({ listingId })
  });
  assert(Array.isArray(toggleSaved.json), "Saved listing toggle response is invalid.");
  assert(toggleSaved.json.includes(listingId), "Saved listing was not persisted.");
  console.log("[smoke] Saved listing toggle passed");

  const saveSearch = await request("/api/saved/searches", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-user-email": email,
      "x-device-id": deviceId
    },
    body: JSON.stringify({
      query: { mode: "buy", text: "Austin", minBeds: 2 }
    })
  });
  assert(Array.isArray(saveSearch.json), "Saved search response is invalid.");
  console.log("[smoke] Saved search persistence passed");

  const frontSearchPage = await fetch(`${baseUrl}/search`);
  assert(frontSearchPage.ok, "Frontend /search route is not reachable.");
  const frontHostPage = await fetch(`${baseUrl}/host`);
  assert(frontHostPage.ok, "Frontend /host route is not reachable.");
  console.log("[smoke] Frontend routes passed");

  console.log("[smoke] Full-stack smoke test passed");
}

run().catch((error) => {
  console.error("[smoke] Test failed");
  console.error(error);
  process.exit(1);
});
